### ISSUE TITLE
pcap_open_live read timeout value

### ISSUE THREAD

**Issue by ov3rlord4** [eclipse/titan.TestPorts.LANL2asp#1]
I met a problem with you implementation of LANL2 port. When a port was listening to an interface and a packet which matched the filter arrived it was not immediately delivered to the callback function. After an apparently random time the callback function was called. I fixed this issue by modifying the read timeout (to_ms according to pcap docs) from 0 to 100. My test was running on Alpine dockers so the problem was probably due to that.

**Comment by ethgasz** [comment]
According to the documentation, the
"The read timeout is used to arrange that the read not necessarily return immediately when a packet is seen, but that it wait for some amount of time to allow more packets to arrive and to read multiple packets from the OS kernel in one operation"

It is possible to use immediate mode, in immediate mode, packets are always delivered as soon as they arrive, with no buffering.

We'll introduce a test port parameter to control the read timeout.
